version: '3.8'

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: shipping_user
      POSTGRES_PASSWORD: shipping_pass
      POSTGRES_DB: shipping_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://shipping_user:shipping_pass@db:5432/shipping_db
    volumes:
      - .:/app
    command: ["python"]

volumes:
  pgdata:
