version: 2

models:
  - name: stg_telegram_messages
    description: "Staging model for scraped Telegram messages"
    columns:
      - name: message_id
        description: "The unique identifier for the message"
        tests:
          - unique
          - not_null
      - name: message_timestamp
        description: "Timestamp when the message was sent"
        tests:
          - not_null
      - name: channel_username
        description: "Username of the channel (@handle)"
      - name: view_count
        description: "Number of views the message received"
      - name: has_image
        description: "Boolean indicating if the message contains an image"

  - name: stg_image_detections
    description: >
      Staging view for YOLO object detections extracted from Telegram message images.
      Links detected object classes with corresponding messages via message_id.
    columns:
      - name: detection_id
        description: Unique identifier for each object detection (surrogate key).
      - name: message_id
        description: Foreign key referencing the Telegram message containing the image.
      - name: detected_object_class
        description: Name of the detected object class (e.g., 'person', 'car').
      - name: confidence_score
        description: Confidence score of the detected object (range: 0 to 1).
      - name: image_filename
        description: Name of the image file that was analyzed.
      - name: relative_path
        description: Path to the image relative to the base data directory.
      - name: processed_at
        description: Timestamp when YOLO processed the image.
      - name: loaded_at
        description: Timestamp when the detection was loaded into the raw layer.
