version: 2

models:
  - name: stg_telegram_messages
    description: "Staging model for scraped Telegram messages"
    columns:
      - name: message_id
        description: "The unique identifier for the message"
        tests:
          - unique
          - not_null
      - name: message_timestamp
        description: "Timestamp when the message was sent"
        tests:
          - not_null
      - name: channel_username
        description: "Username of the channel (@handle)"
      - name: view_count
        description: "Number of views the message received"
      - name: has_image
        description: "Boolean indicating if the message contains an image"