version: 2

models:
  - name: fct_messages
    description: Fact table for Telegram messages
    columns:
      - name: message_id
        tests:
          - unique
          - not_null
      - name: channel_id
        tests:
          - not_null

  - name: dim_channels
    description: Unique list of channel IDs from messages
    columns:
      - name: channel_id
        tests:
          - unique
          - not_null

  - name: dim_dates
    description: Date dimension
    columns:
      - name: date
        tests:
          - unique
          - not_null
